### PR TITLE
Switch to libdatachannel as RTC library. Add GDExtension support.

### PR DESCRIPTION
**Pull request by Faless**
We can finally ditch that ugly mess that's the chromium WebRTC library thanks to a [sane implementation](https://github.com/paullouisageneau/libdatachannel#dependencies): [libdatachannel](https://github.com/paullouisageneau/libdatachannel).

This PR also adds GDExtension (godot 4) support. See the updated [README](https://github.com/Faless/webrtc-native/blob/eb40f13d16768a14fb111b173ca09715ca3fbddb/README.md).

Draft status:

- [x] Waiting for: Godot 4: (EDIT: local fix to work with current upstream) ~godotengine/godot-cpp#762~
- [x] Waiting for: Godot 3: godotengine/godot-cpp#691
- [x] ~Separate main/release CI (`gdnative/vx.y.z` `gdextension/vx.y.z`)~ Build both gdnative and gdextension in CI.
- [x] Need to call `WebRTCLibPeerConnection.new().make_default()` once to bind with the default implementation. (Waiting for godotengine/godot#61839).
- [x] Few `TODO`s to evaluate.

See [here](https://github.com/Faless/webrtc-native/releases/tag/v0.99.1-pr) for prebuilt binaries (current master as of writing, but might break before Godot 4 is released).

### CODE REVIEW

**Comment by dsnopek** [comment]
I compiled the Godot 3 version per your instructions on Twitter (`scons godot_version=3 arch=x86_64`) and it worked in a couple minutes of testing with a real game! It's nice not to see the see console spam that the Google implementation generates. :-)

I'll try to test the Godot 4 version soon as well.

**Comment by dsnopek** [comment]
I haven't managed to do a really solid test of the Godot 4 version yet, but I just wanted to point out that the paths are mostly wrong in the *.gdextension files in the binary release linked in the issue description. It's got them all with "x86_32" in their filenames, rather than the correct architecture:

```
linux.x86_64 = "res://webrtc_debug/lib/libwebrtc_native.linux.debug.x86_32.so"
linux.x86 = "res://webrtc_debug/lib/libwebrtc_native.linux.debug.x86_32.so"
osx.x86_64 = "res://webrtc_debug/lib/libwebrtc_native.osx.debug.x86_32.dylib"
osx.arm64 = "res://webrtc_debug/lib/libwebrtc_native.osx.debug.x86_32.dylib"
windows.x86_64 = "res://webrtc_debug/lib/libwebrtc_native.windows.debug.x86_32.dll"
windows.x86 = "res://webrtc_debug/lib/libwebrtc_native.windows.debug.x86_32.dll"
android.armv7 = "res://webrtc_debug/lib/libwebrtc_native.android.debug.x86_32.so"
android.arm64 = "res://webrtc_debug/lib/libwebrtc_native.android.debug.x86_32.so"
android.x86_64 = "res://webrtc_debug/lib/libwebrtc_native.android.debug.x86_32.so"
android.x86 = "res://webrtc_debug/lib/libwebrtc_native.android.debug.x86_32.so"
ios.arm64 = "res://webrtc_debug/lib/libwebrtc_native.ios.debug.x86_32.dylib"
ios.x86_64 = "res://webrtc_debug/lib/libwebrtc_native.ios.debug.x86_32.simulator.dylib"
```

My system is Linux 64-bit, so when it tried to load the GDExtension I got this error: `Can't open dynamic library: /home/dsnopek/games/godot4-nakama-webrtc/webrtc_debug/lib/libwebrtc_native.linux.debug.x86_32.so. Error: /home/dsnopek/games/godot4-nakama-webrtc/webrtc_debug/lib/libwebrtc_native.linux.debug.x86_32.so: wrong ELF class: ELFCLASS32`

After I corrected the path, it appears to be loading correctly.

**Comment by Faless** [comment]
Thanks for trying out the PR!
The paths should be fixed now.

**Comment by dsnopek** [comment]
> The paths should be fixed now.

Awesome, thanks!

I've started porting a small-ish WebRTC project to Godot 4. I was hoping to get it done today, but that may have been a little optimistic. :-) I'll come back to it on the weekend, and let you know how it goes!

**Comment by dsnopek** [comment]
I ported my "WebRTC and Nakama addon" to Godot 4:

https://gitlab.com/snopek-games/godot-nakama-webrtc/-/commits/godot-4

... and, using the binary builds linked above, got the demo game actually working!

Skimming the code changes, everything _seems_ fine to me. It's very clever how you have it supporting both GDNative and GDExtension :-)

**Review by dsnopek — APPROVED** [review]

**Comment by fire** [comment]
https://github.com/godotengine/godot/pull/61839 merged

**Comment by Faless** [comment]
Updated [the test release](https://github.com/Faless/webrtc-native/releases/tag/v0.99.1-pr) with a GDNative (Godot 3.5) version.

**Pull request merged**
